set ns [new Simulator]

set nf [open out.nam w]
$ns namtrace-all $nf


# Create nodes
set n0 [$ns node]
set n1 [$ns node]
set n2 [$ns node]
set n3 [$ns node]
set n4 [$ns node]
set n5 [$ns node]
set n6 [$ns node]
set n7 [$ns node]
set n8 [$ns node]
set n9 [$ns node]
set n10 [$ns node]
set n11 [$ns node]
set n12 [$ns node]
set n13 [$ns node]
set n14 [$ns node]
set n15 [$ns node]
set n16 [$ns node]
set n17 [$ns node]
set n18 [$ns node]
set n19 [$ns node]
set n20 [$ns node]
set n21 [$ns node]
set n22 [$ns node]
set n23 [$ns node]
set n24 [$ns node]
set n25 [$ns node]
set n26 [$ns node]
set n27 [$ns node]
set n28 [$ns node]
set n29 [$ns node]
set n30 [$ns node]
set n31 [$ns node]
set n32 [$ns node]
set n33 [$ns node]
set n34 [$ns node]
set n35 [$ns node]
set n36 [$ns node]
set n37 [$ns node]
set n38 [$ns node]
set n39 [$ns node]
set n40 [$ns node]
set n41 [$ns node]
set n42 [$ns node]
set n43 [$ns node]
set n44 [$ns node]
set n45 [$ns node]
set n46 [$ns node]
set n47 [$ns node]
set n48 [$ns node]
set n49 [$ns node]
set n50 [$ns node]
set n51 [$ns node]
set n52 [$ns node]
set n53 [$ns node]
set n54 [$ns node]
set n55 [$ns node]
set n56 [$ns node]
set n57 [$ns node]
set n58 [$ns node]
set n59 [$ns node]
set n60 [$ns node]
set n61 [$ns node]
set n62 [$ns node]
set n63 [$ns node]
set n64 [$ns node]
set n65 [$ns node]
set n66 [$ns node]
set n67 [$ns node]
set n68 [$ns node]
set n69 [$ns node]
set n70 [$ns node]
set n71 [$ns node]
set n72 [$ns node]
set n73 [$ns node]
set n74 [$ns node]
set n75 [$ns node]
set n76 [$ns node]
set n77 [$ns node]
set n78 [$ns node]
set n79 [$ns node]
set n80 [$ns node]
set n81 [$ns node]
set n82 [$ns node]
set n83 [$ns node]
set n84 [$ns node]
set n85 [$ns node]
set n86 [$ns node]
set n87 [$ns node]
set n88 [$ns node]
set n89 [$ns node]
set n90 [$ns node]
set n91 [$ns node]
set n92 [$ns node]
set n93 [$ns node]
set n94 [$ns node]
set n95 [$ns node]
set n96 [$ns node]
set n97 [$ns node]
set n98 [$ns node]
set n99 [$ns node]
set n100 [$ns node]
set n101 [$ns node]
set n102 [$ns node]
set n103 [$ns node]
set n104 [$ns node]
set n105 [$ns node]
set n106 [$ns node]
set n107 [$ns node]
set n108 [$ns node]
set n109 [$ns node]




set tcp0 [new Agent/TCP/Reno]
set tcp1 [new Agent/TCP/Reno]
set tcp2 [new Agent/TCP/Reno]
set tcp3 [new Agent/TCP/Reno]
set tcp4 [new Agent/TCP/Reno]
set tcp5 [new Agent/TCP/Reno]
set tcp6 [new Agent/TCP/Reno]
set tcp7 [new Agent/TCP/Reno]
set tcp8 [new Agent/TCP/Reno]
set tcp9 [new Agent/TCP/Reno]
set tcp10 [new Agent/TCP/Reno]
set tcp11 [new Agent/TCP/Reno]
set tcp12 [new Agent/TCP/Reno]
set tcp13 [new Agent/TCP/Reno]
set tcp14 [new Agent/TCP/Reno]
set tcp15 [new Agent/TCP/Reno]
set tcp16 [new Agent/TCP/Reno]
set tcp17 [new Agent/TCP/Reno]
set tcp18 [new Agent/TCP/Reno]
set tcp19 [new Agent/TCP/Reno]
set tcp20 [new Agent/TCP/Reno]
set tcp21 [new Agent/TCP/Reno]
set tcp22 [new Agent/TCP/Reno]
set tcp23 [new Agent/TCP/Reno]
set tcp24 [new Agent/TCP/Reno]
set tcp25 [new Agent/TCP/Reno]
set tcp26 [new Agent/TCP/Reno]
set tcp27 [new Agent/TCP/Reno]
set tcp28 [new Agent/TCP/Reno]
set tcp29 [new Agent/TCP/Reno]
set tcp30 [new Agent/TCP/Reno]
set tcp31 [new Agent/TCP/Reno]
set tcp32 [new Agent/TCP/Reno]
set tcp33 [new Agent/TCP/Reno]
set tcp34 [new Agent/TCP/Reno]
set tcp35 [new Agent/TCP/Reno]
set tcp36 [new Agent/TCP/Reno]
set tcp37 [new Agent/TCP/Reno]
set tcp38 [new Agent/TCP/Reno]
set tcp39 [new Agent/TCP/Reno]
set tcp40 [new Agent/TCP/Reno]
set tcp41 [new Agent/TCP/Reno]
set tcp42 [new Agent/TCP/Reno]
set tcp43 [new Agent/TCP/Reno]
set tcp44 [new Agent/TCP/Reno]
set tcp45 [new Agent/TCP/Reno]
set tcp46 [new Agent/TCP/Reno]
set tcp47 [new Agent/TCP/Reno]
set tcp48 [new Agent/TCP/Reno]
set tcp49 [new Agent/TCP/Reno]
set tcp50 [new Agent/TCP/Reno]
set tcp51 [new Agent/TCP/Reno]
set tcp52 [new Agent/TCP/Reno]
set tcp53 [new Agent/TCP/Reno]
set tcp54 [new Agent/TCP/Reno]
set tcp55 [new Agent/TCP/Reno]
set tcp56 [new Agent/TCP/Reno]
set tcp57 [new Agent/TCP/Reno]
set tcp58 [new Agent/TCP/Reno]
set tcp59 [new Agent/TCP/Reno]
set tcp60 [new Agent/TCP/Reno]
set tcp61 [new Agent/TCP/Reno]
set tcp62 [new Agent/TCP/Reno]
set tcp63 [new Agent/TCP/Reno]
set tcp64 [new Agent/TCP/Reno]
set tcp65 [new Agent/TCP/Reno]
set tcp66 [new Agent/TCP/Reno]
set tcp67 [new Agent/TCP/Reno]
set tcp68 [new Agent/TCP/Reno]
set tcp69 [new Agent/TCP/Reno]
set tcp70 [new Agent/TCP/Reno]
set tcp71 [new Agent/TCP/Reno]
set tcp72 [new Agent/TCP/Reno]
set tcp73 [new Agent/TCP/Reno]
set tcp74 [new Agent/TCP/Reno]
set tcp75 [new Agent/TCP/Reno]
set tcp76 [new Agent/TCP/Reno]
set tcp77 [new Agent/TCP/Reno]
set tcp78 [new Agent/TCP/Reno]
set tcp79 [new Agent/TCP/Reno]
set tcp80 [new Agent/TCP/Reno]
set tcp81 [new Agent/TCP/Reno]
set tcp82 [new Agent/TCP/Reno]
set tcp83 [new Agent/TCP/Reno]
set tcp84 [new Agent/TCP/Reno]
set tcp85 [new Agent/TCP/Reno]
set tcp86 [new Agent/TCP/Reno]
set tcp87 [new Agent/TCP/Reno]
set tcp88 [new Agent/TCP/Reno]
set tcp89 [new Agent/TCP/Reno]
set tcp90 [new Agent/TCP/Reno]
set tcp91 [new Agent/TCP/Reno]
set tcp92 [new Agent/TCP/Reno]
set tcp93 [new Agent/TCP/Reno]
set tcp94 [new Agent/TCP/Reno]
set tcp95 [new Agent/TCP/Reno]
set tcp96 [new Agent/TCP/Reno]
set tcp97 [new Agent/TCP/Reno]
set tcp98 [new Agent/TCP/Reno]
set tcp99 [new Agent/TCP/Reno]
set tcp100 [new Agent/TCP/Reno]
set tcp101 [new Agent/TCP/Reno]
set tcp102 [new Agent/TCP/Reno]
set tcp103 [new Agent/TCP/Reno]
set tcp104 [new Agent/TCP/Reno]
set tcp105 [new Agent/TCP/Reno]
set tcp106 [new Agent/TCP/Reno]
set tcp107 [new Agent/TCP/Reno]
set tcp108 [new Agent/TCP/Reno]
set tcp109 [new Agent/TCP/Reno]



set sink0 [new Agent/TCPSink]
set sink1 [new Agent/TCPSink]
set sink2 [new Agent/TCPSink]
set sink3 [new Agent/TCPSink]
set sink4 [new Agent/TCPSink]
set sink5 [new Agent/TCPSink]
set sink6 [new Agent/TCPSink]
set sink7 [new Agent/TCPSink]
set sink8 [new Agent/TCPSink]
set sink9 [new Agent/TCPSink]
set sink10 [new Agent/TCPSink]
set sink11 [new Agent/TCPSink]
set sink12 [new Agent/TCPSink]
set sink13 [new Agent/TCPSink]
set sink14 [new Agent/TCPSink]
set sink15 [new Agent/TCPSink]
set sink16 [new Agent/TCPSink]
set sink17 [new Agent/TCPSink]
set sink18 [new Agent/TCPSink]
set sink19 [new Agent/TCPSink]
set sink20 [new Agent/TCPSink]
set sink21 [new Agent/TCPSink]
set sink22 [new Agent/TCPSink]
set sink23 [new Agent/TCPSink]
set sink24 [new Agent/TCPSink]
set sink25 [new Agent/TCPSink]
set sink26 [new Agent/TCPSink]
set sink27 [new Agent/TCPSink]
set sink28 [new Agent/TCPSink]
set sink29 [new Agent/TCPSink]
set sink30 [new Agent/TCPSink]
set sink31 [new Agent/TCPSink]
set sink32 [new Agent/TCPSink]
set sink33 [new Agent/TCPSink]
set sink34 [new Agent/TCPSink]
set sink35 [new Agent/TCPSink]
set sink36 [new Agent/TCPSink]
set sink37 [new Agent/TCPSink]
set sink38 [new Agent/TCPSink]
set sink39 [new Agent/TCPSink]
set sink40 [new Agent/TCPSink]
set sink41 [new Agent/TCPSink]
set sink42 [new Agent/TCPSink]
set sink43 [new Agent/TCPSink]
set sink44 [new Agent/TCPSink]
set sink45 [new Agent/TCPSink]
set sink46 [new Agent/TCPSink]
set sink47 [new Agent/TCPSink]
set sink48 [new Agent/TCPSink]
set sink49 [new Agent/TCPSink]
set sink50 [new Agent/TCPSink]
set sink51 [new Agent/TCPSink]
set sink52 [new Agent/TCPSink]
set sink53 [new Agent/TCPSink]
set sink54 [new Agent/TCPSink]
set sink55 [new Agent/TCPSink]
set sink56 [new Agent/TCPSink]
set sink57 [new Agent/TCPSink]
set sink58 [new Agent/TCPSink]
set sink59 [new Agent/TCPSink]
set sink60 [new Agent/TCPSink]
set sink61 [new Agent/TCPSink]
set sink62 [new Agent/TCPSink]
set sink63 [new Agent/TCPSink]
set sink64 [new Agent/TCPSink]
set sink65 [new Agent/TCPSink]
set sink66 [new Agent/TCPSink]
set sink67 [new Agent/TCPSink]
set sink68 [new Agent/TCPSink]
set sink69 [new Agent/TCPSink]
set sink70 [new Agent/TCPSink]
set sink71 [new Agent/TCPSink]
set sink72 [new Agent/TCPSink]
set sink73 [new Agent/TCPSink]
set sink74 [new Agent/TCPSink]
set sink75 [new Agent/TCPSink]
set sink76 [new Agent/TCPSink]
set sink77 [new Agent/TCPSink]
set sink78 [new Agent/TCPSink]
set sink79 [new Agent/TCPSink]
set sink80 [new Agent/TCPSink]
set sink81 [new Agent/TCPSink]
set sink82 [new Agent/TCPSink]
set sink83 [new Agent/TCPSink]
set sink84 [new Agent/TCPSink]
set sink85 [new Agent/TCPSink]
set sink86 [new Agent/TCPSink]
set sink87 [new Agent/TCPSink]
set sink88 [new Agent/TCPSink]
set sink89 [new Agent/TCPSink]
set sink90 [new Agent/TCPSink]
set sink91 [new Agent/TCPSink]
set sink92 [new Agent/TCPSink]
set sink93 [new Agent/TCPSink]
set sink94 [new Agent/TCPSink]
set sink95 [new Agent/TCPSink]
set sink96 [new Agent/TCPSink]
set sink97 [new Agent/TCPSink]
set sink98 [new Agent/TCPSink]
set sink99 [new Agent/TCPSink]
set sink100 [new Agent/TCPSink]
set sink101 [new Agent/TCPSink]
set sink102 [new Agent/TCPSink]
set sink103 [new Agent/TCPSink]
set sink104 [new Agent/TCPSink]
set sink105 [new Agent/TCPSink]
set sink106 [new Agent/TCPSink]
set sink107 [new Agent/TCPSink]
set sink108 [new Agent/TCPSink]
set sink109 [new Agent/TCPSink]



$ns attach-agent $n0 $tcp

set ftp [new Application/FTP]

# send and receive buffer 2gb
# remove cap for 
# delack count 1
$ftp attach-agent $tcp

set null0 [new Agent/TCPSink]
$null0 set total_ 1048576

set n1 [$ns node]
$ns attach-agent $n1 $null0

$ns connect $tcp $null0 

$ns duplex-link $n0 $n1 1Gb 20ms DropTail
$ns queue-limit $n0 $n1 10000


Application/FTP instproc start {} {
	[$self agent] send 1048576
}

$ns at 0 "$ftp start"


proc record {} {
	global ns nf null0 tcp
	set w [$tcp set cwnd_]
	set ss [$tcp set ssthresh_]
	set b [$null0 set bytes_]
	set t [$null0 set total_]
	set now [$ns now]
	puts "$w"
	puts "$ss"
	puts "$b"
	puts "$t"
	puts "$now"

}

proc finish {} {
	global ns nf
	$ns flush-trace
	close $nf
	exec nam out.nam &
	exit 0
}

$ns at 5 "finish"
$ns run

